#!/usr/bin/env bash
# Puts an "AI Tutor" app icon on the macOS desktop that launches the whole
# stack (backend + frontend + borderless window) with one double-click.
# The Windows counterpart is scripts/create-shortcut.ps1.
#
# USAGE
#   ./scripts/create-shortcut.sh              # ~/Desktop/AI Tutor.app
#   ./scripts/create-shortcut.sh ~/Applications
#
# Re-run it any time; it replaces its own bundle in place. Run it after moving
# the repo, too - the bundle stores an absolute path to it.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
icon_src="$repo_root/apps/desktop/assets/AI-Tutor.icns"
bundle_id="com.aitutor.poc.launcher"

dest_dir="${1:-$HOME/Desktop}"
app="$dest_dir/AI Tutor.app"

if [ "$(uname -s)" != "Darwin" ]; then
  echo "This script builds a macOS .app bundle. On Windows use scripts\\create-shortcut.ps1." >&2
  exit 1
fi
if [ ! -f "$icon_src" ]; then
  echo "Icon not found at $icon_src - regenerate it with: node scripts/generate-icons.mjs" >&2
  exit 1
fi
if [ ! -d "$dest_dir" ]; then
  echo "Destination folder does not exist: $dest_dir" >&2
  exit 1
fi

# Node lives outside the minimal PATH that Finder hands a GUI-launched process
# (/usr/bin:/bin:/usr/sbin:/sbin), so `npm run dev` inside the bundle would
# fail with "command not found" even though it works in the terminal. Bake in
# the PATH of the shell creating the shortcut, which by definition can already
# find node, and keep the usual install dirs as a fallback.
node_path="$(command -v node || true)"
if [ -z "$node_path" ]; then
  echo "node is not on PATH. Install Node 18+ and re-run, so the shortcut can find it." >&2
  exit 1
fi
# Prefer the login shell's PATH over this script's own: whatever ran this could
# be a tool with an unusual environment, whereas the login shell's PATH is the
# one that reflects how node/npm were actually installed on this machine.
login_path="$("${SHELL:-/bin/zsh}" -lc 'printf %s "$PATH"' 2>/dev/null || true)"
baked_path="$(dirname "$node_path"):/opt/homebrew/bin:/usr/local/bin:${login_path:-$PATH}"

# Only ever replace a bundle we built. Anything else sharing the name is
# someone else's app, and blowing it away is not this script's call.
if [ -e "$app" ]; then
  existing_id="$(defaults read "$app/Contents/Info" CFBundleIdentifier 2>/dev/null || echo "")"
  if [ "$existing_id" != "$bundle_id" ]; then
    echo "Refusing to overwrite $app - it isn't a bundle this script created" >&2
    echo "(its identifier is '${existing_id:-unknown}', expected '$bundle_id'). Move it aside first." >&2
    exit 1
  fi
  rm -rf "$app"
fi

mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
cp "$icon_src" "$app/Contents/Resources/AI-Tutor.icns"
printf 'APPL????' > "$app/Contents/PkgInfo"

cat > "$app/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>AI Tutor</string>
  <key>CFBundleDisplayName</key><string>AI Tutor</string>
  <key>CFBundleIdentifier</key><string>$bundle_id</string>
  <key>CFBundleExecutable</key><string>AI Tutor</string>
  <key>CFBundleIconFile</key><string>AI-Tutor</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
</dict>
</plist>
PLIST

# The bundle's executable. The repo path and PATH are written in as literals
# (printf %q quotes them safely) so the rest can stay a fully literal heredoc.
exec_path="$app/Contents/MacOS/AI Tutor"
{
  printf '#!/bin/bash\n'
  printf '# Generated by scripts/create-shortcut.sh - edit that, not this.\n'
  printf 'REPO_ROOT=%q\n' "$repo_root"
  printf 'export PATH=%q\n' "$baked_path"
  cat <<'LAUNCHER'

# Finder gives a bundle no console, so everything goes to a log next to the
# repo and anything fatal is raised as a real dialog - otherwise a failed
# launch would just be a Dock icon that bounces once and vanishes.
LOG="$REPO_ROOT/desktop-launcher.log"
: > "$LOG"
exec >>"$LOG" 2>&1
echo "=== AI Tutor launch $(date) ==="

fail() {
  osascript \
    -e 'on run argv' \
    -e 'display dialog (item 1 of argv) with title "AI Tutor" buttons {"OK"} default button 1 with icon stop' \
    -e 'end run' \
    "$1" >/dev/null 2>&1
  exit 1
}

[ -x "$REPO_ROOT/scripts/start.sh" ] || fail "Couldn't find the AI Tutor project at:

$REPO_ROOT

If you moved or renamed the folder, re-run scripts/create-shortcut.sh from its new location."

# start.sh holds the stack open for the whole session, so it has to outlive
# this launcher - the Dock icon should stop bouncing once the window is up,
# not sit there for as long as the app is running.
nohup "$REPO_ROOT/scripts/start.sh" >>"$LOG" 2>&1 &
stack_pid=$!
disown 2>/dev/null || true

# Wait for the Vite dev server launch.mjs opens the window against. Cold
# starts install nothing but do compile, so allow well over the backend's own
# 30s budget before calling it stuck.
for _ in $(seq 1 120); do
  if curl -sf --max-time 1 http://localhost:5180 >/dev/null 2>&1; then
    echo "Window server is up; launcher exiting."
    exit 0
  fi
  if ! kill -0 "$stack_pid" 2>/dev/null; then
    fail "AI Tutor couldn't start.

$(tail -n 12 "$LOG")

Full log: $LOG"
  fi
  sleep 1
done

fail "AI Tutor is taking longer than two minutes to start, so something is probably wrong.

Full log: $LOG"
LAUNCHER
} > "$exec_path"
chmod +x "$exec_path"

# Finder caches icons per bundle; touching the bundle makes it re-read this one
# instead of showing a generic blank page until the next relaunch.
touch "$app"

echo "Created: $app"
echo "Double-click it to start the backend, the frontend and the tutor window."
echo "Logs: $repo_root/desktop-launcher.log (launcher), backend.out.log / backend.err.log (backend)"
echo "To stop everything afterwards: $repo_root/scripts/stop.sh"
